---
title: "Formation-R-perfectionnement"
subtitle: "Module Cartographie"
date: today
date-format: "DD/MM/YYYY"
author: "SSP/DEMESIS"
description: |
  Support de formation R-perfectionnement : Module Cartographie
slide-tone: false # for blind readers
chalkboard: false # press the B key to toggle chalkboard
transition: slide
fig-cap-location: bottom
toc: true
toc-title: Sommaire
toc-depth: 1
toc-float: true
# multiplex: true
execute:
  echo: false
  warning: false
  cache: false
editor:
  render-on-save: true
  markdown: 
    wrap: 72
---

# Avant-propos{.unnumbered}

## Avant-propos

Ce diaporama de formation a été rédigé dans le but d'être le support visuel des formations dispensées au [SSM Agriculture](https://agreste.agriculture.gouv.fr/).

Ces formations _de perfectionnement_ s'adressent aux agents qui ont suivi **la formation R
initialisation** (ou le **module de rappels sur la formation initiation**) ainsi que le **module sur les fonctions**, voir sur le [site des formations dispensées au MASA](https://ssm-agriculture.github.io/site-formations-R/).

## Avant-propos

Les différents modules sont donnés en présentiel sur une durée **d'une journée** (avant la formation _R-perfectionnement_ était groupée sur 3 jours).

::: callout-note
## Champ couvert par cette formation

**Ce support couvre le module cartographie dans l'environnement du Ministère.**

Pour information, Les Modules de la formation R-perfectionnement sont :

-   01 - Module Rappels
-   02 - Module Fonctions
-   03 - Module Quarto 
-   04 - Module Création de graphiques avec `ggplot2`
-   05 - Module Cartes statiques et interactives
-   06 - Module Parquet
-   07 - Module Initiation à l'écriture d'applications Shiny

Les modules sont orientés pour être utiles aux agents du SSM Agriculture et se concentrent sur une utilisation de R via [RStudio](https://posit.co/download/rstudio-desktop/) qui est mise à
disposition des agents sur la plateforme interne Cerise basée sur RStudio Workbench.
:::

{{< include 01_carto.qmd >}}

